---
- hosts: hypervisor
  remote_user: root
  tasks:
    - name: webvirt ssh key
      authorized_key:
        user: "{{ ansible_user_id }}"
        key: "{{ webvirt_ssh_key }}"
      when: webvirt_ssh_key is defined
    - name: cpufreq
      include_tasks: './tasks/cpufreq.yml'
    - name: kernel params
      become: true
      blockinfile:
        path: /etc/default/grub
        marker: '# {mark} KVM kernel param block'
        block: |
          KVM_KERNEL_PARAMS=""
          ## intel only, amd todo.
          KVM_KERNEL_PARAMS="$KVM_KERNEL_PARAMS intel_iommu=on"
          {% if vtd_pci_devices is defined and vtd_pci_devices and vtd_pci_devices | length > 0 %}
          ## Devices for VT-D
          KVM_KERNEL_PARAMS="$KVM_KERNEL_PARAMS vfio-pci.ids={{vtd_pci_devices | join(',')}}"
          {% endif %}
          ## set params
          GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT $KVM_KERNEL_PARAMS"
      when: ansible_os_family == 'Debian' and vtd is defined and vtd
      notify: update_grub
    - name: apt
      become: true
      when: ansible_os_family == 'Debian'
      apt:
        # state: latest
        update_cache: true
        name: qemu,qemu-kvm,bridge-utils,virtinst,libguestfs-tools,ksmtuned,dmidecode,cockpit,cockpit-machines,libvirt-daemon,libvirt-dev,python3,python3-libvirt,python3-lxml,ovmf
    - name: packages for focal
      become: true
      when: ansible_os_family == 'Debian' and (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 11 or ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 20)
      apt:
        name: python-is-python3
    - name: packages for non-focal
      become: true
      when: ansible_os_family == 'Debian' and not (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 11 or ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 20)
      apt:
        name: python,python-libvirt,python-lxml
    - name: epel 7
      become: true
      yum:
        state: latest
        name: epel-release
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7
    - name: yum
      become: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7
      yum:
        state: latest
        update_cache: true
        name: sudo,python,kvm,qemu-kvm,qemu-kvm-tools,qemu-img,libvirt,libvirt-python,libguestfs-tools,bridge-utils,virt-install,python-lxml,dmidecode,cockpit,cockpit-machines
    - name: epel 8
      become: true
      dnf:
        state: latest
        name: epel-release
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
    - name: dnf
      become: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
      dnf:
        state: latest
        name: sudo,python3,qemu-kvm,qemu-img,libvirt,python3-libvirt,libguestfs-tools,virt-install,python3-lxml,dmidecode,cockpit,cockpit-machines
    - name: qemu conf
      become: true
      blockinfile:
        path: /etc/crontab
        marker: '# {mark} MyCard NextGen Router block'
        block: |
          user = "{{ansible_user_id}}"
          group = "{{ansible_user_id}}"
      notify: restart_libvirt
    - name: libvirt service
      become: true
      systemd:
        name: libvirtd
        state: started
        enabled: true
    - name: ksmtuned
      become: true
      systemd:
        name: ksmtuned
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'
    - name: stop firewalld
      become: true
      systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: ansible_os_family == 'RedHat'
    - name: permission for home path
      become: true
      file:
        path: '{{home_path}}'
        state: directory
        owner: '{{ansible_user_id}}'
        group: '{{ansible_user_id}}'
    - name: pool directories
      file:
        path: '{{home_path}}/{{item}}'
        state: directory
      with_items:
        - iso
        - img
        - xml
    - name: cockpit cert
      become: true
      copy:
        src: '../certs/{{cockpit_cert_domain}}/{{item.file}}'
        dest: /etc/cockpit/ws-certs.d/0-self-signed.{{item.suffix}}
        owner: root
        group: cockpit-ws
        mode: 0640
      notify: restart_cockpit
      when: cockpit_cert_domain is defined
      with_items:
        - file: cert.pem
          suffix: cert
        - file: privkey.pem
          suffix: key
  handlers:
    - name: restart_cockpit
      become: true
      systemd:
        name: cockpit
        state: restarted
    - name: restart_libvirt
      become: true
      systemd:
        name: libvirtd
        state: restarted
    - name: update_grub
      become: true
      shell: update-grub
