---
- hosts: hypervisor
  remote_user: root
  tasks:
    - name: authorized_key
      authorized_key:
        user: "{{ ansible_user_id }}"
        key: "{{ webvirt_ssh_key }}"
    - name: get cpufreq policy path
      find:
        paths:
          - /sys/devices/system/cpu/cpufreq/
        file_type: directory
      register: freq_list
    - name: cpufreq
      become: true
      copy:
        content: '{{cpupower}}'
        dest: '{{item.path}}/scaling_governor'
        unsafe_writes: true
      with_items: '{{freq_list.files}}'
    - name: apt
      become: true
      when: "ansible_os_family == 'Debian'"
      apt:
        state: latest
        update_cache: true
        name: sudo,python,qemu,qemu-kvm,libvirt-bin,bridge-utils,virtinst,libguestfs-tools,python-libvirt,python-lxml,ksmtuned
    - name: epel 7
      become: true
      yum:
        state: latest
        name: epel-release
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7"
    - name: yum
      become: true
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7"
      yum:
        state: latest
        update_cache: true
        name: sudo,python,kvm,qemu-kvm,qemu-kvm-tools,qemu-img,libvirt,libvirt-python,libguestfs-tools,bridge-utils,virt-install,python-lxml
    - name: epel 8
      become: true
      dnf:
        state: latest
        name: epel-release
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
    - name: dnf
      become: true
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
      dnf:
        state: latest
        name: sudo,python3,qemu-kvm,qemu-img,libvirt,python3-libvirt,libguestfs-tools,virt-install,python3-lxml
    - name: libvirt service
      become: true
      systemd:
        name: libvirtd
        state: started
        enabled: true
    - name: ksmtuned
      become: true
      systemd:
        name: ksmtuned
        state: started
        enabled: true
      when: "ansible_os_family == 'Debian'"
    - name: stop firewalld
      become: true
      systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: "ansible_os_family == 'RedHat'"
    - name: flush forward table
      become: true
      iptables:
        chain: FORWARD
        flush: true
    - name: iptables save
      shell: 'sudo iptables-save > ~/ipt'
    - name: iptables forward script
      copy:
        src: files/hypervisor/iptables-forward.sh
        dest: '~/iptables-forward.sh'
        mode: 0755
    - name: permission for home path
      become: true
      file:
        path: '{{home_path}}'
        state: directory
        owner: '{{ansible_user_id}}'
        group: '{{ansible_user_id}}'
    - name: pool directories
      file:
        path: '{{home_path}}/{{item}}'
        state: directory
      with_items:
        - iso
        - img
        - xml
