---
- hosts: hypervisor
  remote_user: root
  tasks:
    - name: cockpit cert
      become: true
      copy:
        src: '../certs/{{cockpit_cert_domain}}/{{item.file}}'
        dest: /etc/cockpit/ws-certs.d/0-self-signed.{{item.suffix}}
        owner: root
        group: cockpit-ws
        mode: 0640
      notify: restart_cockpit
      with_items:
        - file: cert.pem
          suffix: cert
        - file: privkey.pem
          suffix: key
    - name: start cockpit
      become: true
      systemd:
        name: cockpit
        state: started
        enabled: yes
  handlers:
    - name: restart_cockpit
      become: true
      systemd:
        name: cockpit
        state: restarted
