---
- hosts: srvpro
  remote_user: root
  vars:
    install: true
  #  home_path: ~
  #  fork: mycard
  #  server_type: public
  roles:
    - name: nodejs
      vars:
        nodejs_version: 18
    - name: mono
      when: server_type is not defined or server_type != "tournament"
  tasks:
    - name: apt
      become: true
      apt:
        update_cache: true
        name: wget,git,build-essential,libreadline-dev,libsqlite3-dev,libevent-dev,p7zip-full,liblua5.4-dev
      when: ansible_os_family == 'Debian'
    - name: epel 7
      become: true
      yum:
        update_cache: true
        name: epel-release,curl
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7
    - name: yum
      become: true
      yum:
        update_cache: true
        name: wget,git,gcc,gcc-c++,make,sqlite-devel,readline-devel,openssl-devel,libevent-devel,p7zip,p7zip-plugins,tar,unzip
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7
    - name: epel 8
      become: true
      dnf:
        name: epel-release
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
    - name: dnf
      become: true
      dnf:
        name: curl,wget,gcc,gcc-c++,make,sqlite-devel,readline-devel,openssl-devel,libevent-devel,p7zip,p7zip-plugins,tar,unzip
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
    - name: ygopro
      include_tasks: ./tasks/srvpro/ygopro.yml
      vars:
        ygopro_path: '{{home_path}}/ygopro'
    - name: common
      include_tasks: ./tasks/srvpro/common.yml
    - name: stop firewalld
      become: true
      ignore_errors: true
      systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: ansible_os_family == 'RedHat'
