---
- hosts: init
  tasks:
    - name: install latest docker
      become: true
      apt:
        name: docker-ce,docker-ce-cli,docker-compose-plugin
        state: latest
        update_cache: yes
      notify: restart_docker
    - name: docker-compose
      become: true
      pip:
        name: docker-compose,docker==6.1.3,requests==2.31.0
        extra_args: '--no-build-isolation --ignore-installed'
    - name: replace compose/service.py 
      become: true
      copy:
        src: ./files/docker-service-patch.py
        dest: "/usr/local/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/dist-packages/compose/service.py"
        backup: yes
  handlers:
    - name: restart_docker
      become: true
      systemd:
        name: docker
        state: restarted
