---
- hosts: pter
  remote_user: root
  tasks:
    - name: set template
      set_fact:
        config_content:
          debug: false
          uuid: '{{uuid}}'
          token_id: '{{token_id}}'
          token: '{{token}}'
          api:
            host: 0.0.0.0
            port: '{{https_port}}'
            ssl:
              enabled: true
              cert: '/certs/fullchain.pem'
              key: '/certs/privkey.pem'
            upload_limit: 100
          system:
            data: '{{data_path}}'
            sftp:
              bind_port: '{{sftp_port}}'
          allowed_mounts: []
          remote: '{{remote}}'
        docker_compose_content:
          version: '2.4'
          services:
            pterodactyl:
              restart: always
              image: ccarney16/pterodactyl-daemon:v1.6.1
              network_mode: host
              environment:
                TZ: Asia/Shanghai
              volumes:
                - /etc/localtime:/etc/localtime:ro
                - /var/run/docker.sock:/var/run/docker.sock
                - ./certs:/certs:ro
                - ./config.yml:/etc/pterodactyl/config.yml
                - '{{data_path}}:{{data_path}}'
    - name: directory
      file:
        path: '{{ansible_user_dir}}/pterodactyl/certs'
        state: directory
        recurse: true
    - name: config file
      copy:
        content: '{{config_content | to_yaml}}'
        dest: '{{ansible_user_dir}}/pterodactyl/config.yml'
      notify: restart_pterodactyl
    - name: docker-compose.yml
      copy:
        content: '{{docker_compose_content | to_yaml}}'
        dest: '{{ansible_user_dir}}/pterodactyl/docker-compose.yml'
    - name: cert file
      copy:
        src: '../certs/{{cert_domain}}/{{item}}.pem'
        dest: '{{ansible_user_dir}}/pterodactyl/certs/{{item}}.pem'
        mode: '0644'
      with_items:
        - fullchain
        - privkey
      notify: restart_pterodactyl
    - name: docker-compose up -d
      docker_compose:
        project_src: '{{ansible_user_dir}}/pterodactyl'
        remove_orphans: true
        pull: true
  handlers:
    - name: restart_pterodactyl
      include_tasks: 'handlers/docker.yaml'
      vars:
        handler: 
          type: docker
          path: '{{ansible_user_dir}}/pterodactyl'
          services:
            - pterodactyl
