---
- hosts: pter
  remote_user: root
  tasks:
    - name: set template
      set_fact:
        docker_compose_content:
          version: '2.4'
          services:
            pterodactyl:
              restart: always
              image: ccarney16/pterodactyl-daemon:v1.6.1
              network_mode: host
              environment:
                TZ: Asia/Shanghai
              volumes:
                - /etc/localtime:/etc/localtime:ro
                - /var/run/docker.sock:/var/run/docker.sock
                - ./certs:/certs:ro
                - ./config.yml:/etc/pterodactyl/config.yml
                - '{{data_path}}:{{data_path}}'
                - /tmp/pterodactyl:/tmp/pterodactyl
    - name: directory
      file:
        path: '{{ansible_user_dir}}/pterodactyl/certs'
        state: directory
        recurse: true
    - name: config file
      template:
        src: ./files/pter/config.yml.j2
        dest: '{{ansible_user_dir}}/pterodactyl/config.yml'
      notify: restart_pterodactyl
    - name: docker-compose.yml
      copy:
        content: '{{docker_compose_content | to_yaml}}'
        dest: '{{ansible_user_dir}}/pterodactyl/docker-compose.yml'
    - name: cert file
      copy:
        src: '../certs/{{cert_domain}}/{{item}}.pem'
        dest: '{{ansible_user_dir}}/pterodactyl/certs/{{item}}.pem'
        mode: '0644'
      with_items:
        - fullchain
        - privkey
      notify: restart_pterodactyl
    - name: docker-compose up -d
      docker_compose:
        project_src: '{{ansible_user_dir}}/pterodactyl'
        remove_orphans: true
        pull: true
  handlers:
    - name: restart_pterodactyl
      include_tasks: 'handlers/docker.yaml'
      vars:
        handler: 
          type: docker
          path: '{{ansible_user_dir}}/pterodactyl'
          services:
            - pterodactyl
