---
- hosts: pter
  remote_user: root
  vars:
    nodejs_version: 10
  tasks:
    - name: nodejs
      include: includes/nodejs.yml
    - name: docker
      include: includes/docker.yml
    - name: apt
      apt:
        update_cache: true
        state: latest
        name: curl,wget,build-essential,tar,unzip,python,rsync
    - name: directories
      file:
        path: '/srv/{{item}}'
        state: directory
      with_items:
        - daemon
        - daemon-data
    - name: download daemon
      unarchive:
        src: https://github.com/pterodactyl/daemon/releases/download/v0.6.12/daemon.tar.gz
        dest: /srv/daemon
        creates: /srv/daemon/src
        remote_src: true
        extra_opts:
          - --strip-components=1
    - name: npm install
      npm:
        path: /srv/daemon
        production: true
    - name: core.json
      template:
        src: files/pter/pter.json.j2
        dest: /srv/daemon/config/core.json
      notify: launch
    - name: certs
      synchronize:
        src: '{{ cert_path }}/'
        dest: /srv/certs
        delete: true
      notify: launch
  handlers:
    - name: launch
      shell: 'pm2 start src/index.js --name daemon && pm2 save && pm2 startup'
      args:
        chdir: /srv/daemon
      ignore_errors: true
