- hosts: fileserver
  remote_user: root
  tasks:
    - name: directory
      file:
        path: '{{docker_compose_path}}'
        state: directory
    - name: docker-compose file
      copy:
        src: './files/samba-data/{{ inventory_hostname_short }}/docker-compose.yml'
        dest: '~/fileserver/docker-compose.yml'
    - name: docker-compose up -d
      docker_compose:
        project_src: ~/fileserver
        remove_orphans: true
