---
- hosts: ocserv
  remote_user: root
  tasks:
    - name: Update OCServ Compose without restarting
      template:
        src: files/services/ocserv/docker-compose.yml.j2
        dest: '{{ ansible_user_dir }}/{{ service_path }}/docker-compose.yml'
    - name: Install VPN pool fallback
      become: true
      command: ip route replace blackhole {{ network }}

- hosts: outer-railgun-client:ns-slave
  remote_user: root
  vars:
    compose_command: "{{ 'docker compose' if v2_format | default(false) else 'docker-compose' }}"
    leaf_subnets: "{{ subnets if service_name == 'outer-railgun-client' else [ip_prefix ~ '.' ~ ns_id ~ '/29'] }}"
  tasks:
    - name: Add routing leaf to existing Compose
      blockinfile:
        path: '{{ ansible_user_dir }}/{{ service_path }}/docker-compose.yml'
        insertafter: '^services:'
        marker: '  # {mark} routing leaf'
        block: |2
            routing-client:
              image: git-registry.moenext.com/railgun/railgun-routing-client:rust
              network_mode: host
              restart: always
              command: {{ (['leaf', routing_parent ~ ':258'] + leaf_subnets) | to_json }}
    - name: Pull routing leaf only
      command: '{{ compose_command }} pull routing-client'
      args:
        chdir: '{{ ansible_user_dir }}/{{ service_path }}'
    - name: Start routing leaf only
      command: '{{ compose_command }} up -d --no-deps routing-client'
      args:
        chdir: '{{ ansible_user_dir }}/{{ service_path }}'
