---
- hosts: template
  remote_user: root
  vars:
    install_fish_and_byobu: false
    authorized_keys: false
    allow_password: true
  tasks:
    - name: tasks from init
      include_tasks: './roles/init/tasks/{{item}}.yml'
      with_items: 
        - utility
        - sshd_config
        - upgrade
        - sshd_config
        - sysctl
    - name: apt
      include_tasks: ./roles/init/tasks/apt.yml
      when: ansible_os_family == 'Debian'
    - name: yum
      include_tasks: ./roles/init/tasks/yum.yml
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
    - name: dnf
      include_tasks: ./roles/init/tasks/dnf.yml
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
    - name: redhat configures
      include_tasks: ./roles/init/tasks/redhat_configures.yml
      when: ansible_os_family == 'RedHat'
    - name: remove hwaddr in ifcfg
      become: true
      shell: 'sed -i "/HWADDR/d" /etc/sysconfig/network-scripts/ifcfg-*'
      when: ansible_os_family == 'RedHat'
    - name: set hostname to localhost
      become: true
      lineinfile:
        path: /etc/sysconfig/network
        line: 'HOSTNAME=localhost.localdomain'
        insertafter: 'EOF'
      when: ansible_os_family == 'RedHat'
    - name: ssh-keygen service
      become: true
      copy:
        content: |
          [Unit]
          Description=Regenerate SSH host keys
          Before=sshd.service
          
          [Service]
          Type=oneshot
          ExecStartPre=/bin/sh -c "/bin/rm -f -v /etc/ssh/ssh_host_*_key*"
          ExecStart=/usr/bin/ssh-keygen -A -v
          ExecStartPost=/bin/systemctl disable regenerate_ssh_host_keys
          
          [Install]
          WantedBy=multi-user.target
        dest: /lib/systemd/system/regenerate_ssh_host_keys.service
    - name: systemd
      become: true
      systemd:
        name: regenerate_ssh_host_keys
        enabled: true
        daemon_reload: true
    - name: motd
      become: true
      copy:
        content: Welcome to MyCard Cloud Service!
        dest: /etc/motd
    - name: clean logs and hostkeys
      become: true
      shell: 'rm -rf /etc/ssh/ssh_host_* /var/log/*'
    - name: clean bash history
      file:
        name: '~/.bash_history'
        state: absent
    - name: poweroff
      become: true
      shell: poweroff
      async: 0
      poll: 0
  handlers:
    - name: restart_sshd
      ping:
