---
- hosts: template
  remote_user: root
  tasks:
    - name: source
      become: true
      copy:
        src: 'files/source/{{ansible_distribution|lower}}/sources.list'
        dest: /etc/apt/sources.list
      when: ansible_os_family == 'Debian'
    - name: sudoers
      become: true
      lineinfile:
        path: /etc/sudoers
        insertafter: 'EOF'
        line: '{{ ansible_user_id }} ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
      when: "ansible_user_id != 'root'"
    - name: timezone
      become: true
      timezone:
        name: Asia/Shanghai
    - name: permit root login
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin (false|no).*$'
        line: 'PasswordAuthentication yes'
        backrefs: true
    - name: sshd config
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?GSSAPIAuthentication (true|yes).*$'
        line: 'GSSAPIAuthentication no'
        backrefs: true
    - name: sshd config
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?UseDNS (true|yes).*$'
        line: 'UseDNS no'
        backrefs: true
    - name: net.ipv4.ip_forward
      become: true
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
    - name: fs.inotify.max_user_watches
      become: true
      sysctl:
        name: fs.inotify.max_user_watches
        value: 524288
        sysctl_set: true
    - name: net.ipv4.conf.all.rp_filter
      become: true
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: 0
        sysctl_set: true
    - name: net.ipv4.conf.default.rp_filter
      become: true
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: 0
        sysctl_set: true
    - name: TCP BBR
      become: true
      sysctl:
        name: net.core.default_qdisc
        value: fq
        sysctl_set: true
      when: "ansible_os_family == 'Debian' or ansible_distribution_major_version|int > 7"
    - name: TCP BBR
      become: true
      sysctl:
        name: net.ipv4.tcp_congestion_control
        value: bbr
        sysctl_set: true
      when: "ansible_os_family == 'Debian' or ansible_distribution_major_version|int > 7"
    - name: limit
      become: true
      pam_limits:
        domain: '{{ ansible_user_id }}'
        limit_type: '-'
        limit_item: nofile
        value: 1048576
    - name: apt upgrade
      become: true
      apt:
        update_cache: true
        upgrade: dist
      when: "ansible_os_family == 'Debian'"
    - name: yum update
      become: true
      yum:
        name: '*'
        update_cache: true
        state: latest
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7"
    - name: dnf update
      become: true
      dnf:
        name: '*'
        #update_cache: true
        state: latest
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
    - name: fixup iptables with qemu
      become: true
      iptables:
        chain: FORWARD
        flush: true
      when: 'hypervisor is defined'
    - name: apt
      become: true
      apt:
        update_cache: true
        state: latest
        name: curl,wget,git,vim,sudo,byobu,iftop,iotop,build-essential,p7zip-full,tcpdump,rsync,htop,locales,mtr,dnsutils,net-tools,traceroute,tar,unzip,iperf,nmap,dnsutils,open-vm-tools
      when: "ansible_os_family == 'Debian'"
    - name: apt autoremove
      become: true
      apt:
        autoremove: true
      when: "ansible_os_family == 'Debian'"
    - name: epel 7
      become: true
      yum:
        state: latest
        name: epel-release
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7"
    - name: yum
      become: true
      yum:
        state: latest
        name: curl,wget,git,vim,sudo,byobu,iftop,iotop,gcc,gcc-c++,make,autoconf,p7zip,p7zip-plugins,tcpdump,rsync,htop,mtr,net-tools,traceroute,tar,unzip,iperf,nmap,libselinux-python,open-vm-tools
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7"
    - name: epel 8
      become: true
      dnf:
        state: latest
        name: epel-release
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
    - name: dnf
      become: true
      dnf:
        state: latest
        name: curl,wget,git,vim,sudo,byobu,iftop,iotop,gcc,gcc-c++,make,autoconf,p7zip,p7zip-plugins,tcpdump,rsync,htop,mtr,net-tools,traceroute,tar,unzip,nmap,python3-libselinux,open-vm-tools
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
    - name: dnf autoremove
      become: true
      dnf:
        autoremove: true
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
    - name: disable selinux
      become: true
      selinux:
        state: disabled
      when: "ansible_os_family == 'RedHat'"
    - name: disable selinux
      become: true
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        backrefs: true
      when: "ansible_os_family == 'RedHat'"
    - name: remove hwaddr in ifcfg
      become: true
      shell: 'sed -i "/HWADDR/d" /etc/sysconfig/network-scripts/ifcfg-*'
      when: "ansible_os_family == 'RedHat'"
    - name: set hostname to localhost
      become: true
      lineinfile:
        path: /etc/sysconfig/network
        line: 'HOSTNAME=localhost.localdomain'
        insertafter: 'EOF'
      when: "ansible_os_family == 'RedHat'"
    - name: ssh-keygen service
      become: true
      copy:
        content: |
          
    - name: clean logs and hostkeys
      become: true
      shell: 'rm -rf /etc/ssh/ssh_host_* /var/log/*'
    - name: clean bash history
      file:
        name: '~/.bash_history'
        state: absent
