---
- hosts: srvpro
  remote_user: root
  vars:
#    home_path: ~
#    fork: mycard
    backup_name: '1120'
  tasks:
    - name: srvpro
      git:
        repo: 'https://github.com/{{fork}}/srvpro'
        dest: '{{home_path}}/ygopro-server'
        force: true
        accept_hostkey: true
        track_submodules: true
    #- name: permission
    #  become: true
    #  file:
    #    path: '{{home_path}}/.npm'
    #    recurse: true
    #    owner: "{{ ansible_user_id }}"
    #- name: srvpro npm
    #  npm:
    #    path: '{{home_path}}/ygopro-server'
    - name: windbot
      git:
        repo: 'https://github.com/{{fork}}/windbot'
        dest: '{{home_path}}/windbot'
        force: true
        accept_hostkey: true
        track_submodules: true
    - name: build windbot
      shell: xbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5
      args:
        chdir: '{{home_path}}/windbot'
    - name: remove deprecated ygopro-new
      file:
        path: '{{home_path}}/ygopro-new'
        state: absent
    - name: premake5
      unarchive:
        src: https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz
        dest: '{{home_path}}/ygopro/'
        remote_src: yes
    - name: ygopro new
      shell: 'cp -rf {{home_path}}/ygopro {{home_path}}/ygopro-new'
    - name: ygopro
      git:
        repo: 'https://github.com/{{fork}}/ygopro'
        dest: '{{home_path}}/ygopro-new'
        force: true
        accept_hostkey: true
        track_submodules: true
    - name: premake5 gmake
      shell: ./premake5 gmake
      args:
        chdir: ‘{{home_path}}/ygopro-new’
    - name: build
      make:
        chdir: ‘{{home_path}}/ygopro-new/build’
        target: config=release
    - name: strip ygopro
      shell: strip bin/release/ygopro
      args:
        chdir: ’{{home_path}}/ygopro-new‘
    - name: remove same backup
      file:
        path: '{{home_path}}/ygopro-bak{{backup_name}}'
        state: absent
    - name: move ygopro
      shell: 'mv {{home_path}}/ygopro {{home_path}}/ygopro-bak{{backup_name}} && mv {{home_path}}/ygopro-new {{home_path}}/ygopro'
