---
- hosts: srvpro
  remote_user: root
  vars:
#    home_path: ~
#    fork: mycard
    backup_name: '{{lookup("pipe","date +%m.%d")}}'
  tasks:
    - name: srvpro
      git:
        repo: 'https://github.com/{{fork}}/srvpro'
        dest: '{{home_path}}/ygopro-server'
        force: true
        accept_hostkey: true
        track_submodules: true
    - name: srvpro npm
      npm:
        path: '{{home_path}}/ygopro-server'
        ci: true
    - name: challonge
      git:
        repo: 'https://github.com/moecube/challonge'
        dest: '{{home_path}}/ygopro-server/challonge'
        version: master
        force: true
        accept_hostkey: true
        track_submodules: true
    - name: windbot
      git:
        repo: 'https://github.com/{{fork}}/windbot'
        dest: '{{home_path}}/windbot'
        force: true
        accept_hostkey: true
        track_submodules: true
      when: 'server_type != "tournament"'
    - name: build windbot
      shell: xbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5
      args:
        chdir: '{{home_path}}/windbot'
      when: 'server_type != "tournament"'
    - name: remove deprecated ygopro-new
      file:
        path: '{{home_path}}/ygopro-new'
        state: absent
    - name: premake5
      unarchive:
        src: https://minio.mycard.moe:9000/nanahira/premake-5.0.0-alpha13-linux.tar.gz
        dest: '{{home_path}}/ygopro/'
        creates: '{{home_path}}/ygopro/premake5'
        remote_src: true
    - name: ygopro new
      shell: 'cp -rf {{home_path}}/ygopro {{home_path}}/ygopro-new'
    - name: ygopro
      git:
        repo: 'https://github.com/{{fork}}/ygopro'
        dest: '{{home_path}}/ygopro-new'
        force: true
        accept_hostkey: true
        track_submodules: true
    - name: premake5 gmake
      shell: ./premake5 gmake
      args:
        chdir: '{{home_path}}/ygopro-new'
      when: 'not no_lua_safe'
    - name: premake5 gmake unsafe
      shell: env YGOPRO_NO_LUA_SAFE=1 ./premake5 gmake
      args:
        chdir: '{{home_path}}/ygopro-new'
      when: 'no_lua_safe'
    - name: build
      make:
        chdir: '{{home_path}}/ygopro-new/build'
        target: 'config=release'
        params:
          NUM_THREADS: '{{ansible_processor_vcpus}}'
    - name: strip ygopro
      shell: strip bin/release/ygopro
      args:
        chdir: '{{home_path}}/ygopro-new'
    - name: remove same backup
      file:
        path: '{{home_path}}/ygopro-backup-{{backup_name}}'
        state: absent
    - name: move ygopro
      shell: 'mv {{home_path}}/ygopro {{home_path}}/ygopro-backup-{{backup_name}} && mv {{home_path}}/ygopro-new {{home_path}}/ygopro'
