---
- hosts: srvpro
  remote_user: root
  vars:
#    home_path: ~
#    fork: mycard
    backup_name: '{{lookup("pipe","date +%m.%d")}}'
    install: false
  tasks:
    - name: remove deprecated ygopro-new
      file:
        path: '{{home_path}}/ygopro-new'
        state: absent
    - name: ygopro new
      shell: 'cp -rf {{home_path}}/ygopro {{home_path}}/ygopro-new'
    - name: ygopro
      include_tasks: ./tasks/srvpro/ygopro.yml
      vars:
        ygopro_path: '{{home_path}}/ygopro-new'
    - name: remove same backup
      file:
        path: '{{home_path}}/ygopro-backup-{{backup_name}}'
        state: absent
    - name: move ygopro
      shell: 'mv {{home_path}}/ygopro {{home_path}}/ygopro-backup-{{backup_name}} && mv {{home_path}}/ygopro-new {{home_path}}/ygopro'
    - name: common
      include_tasks: ./tasks/srvpro/common.yml
    - name: update callback
      shell: '{{update_callback}}'
      when: update_callback is defined and update_callback
