---
- hosts: utility
  remote_user: root
  tasks:
    - name: utility directory
      file:
        path: /root/utility
        state: directory
    - name: related files
      synchronize:
        src: ./files/utility/
        dest: /root/utility
    - name: apt-cacker-ng Dockerfile directory
      file:
        path: /root/utility/apt-cacher-ng-docker
        state: directory
    - name: apt cacher Dockerfile
      template:
        src: ./files/apt-cacher-ng-docker/Dockerfile.j2
        dest: /root/utility/apt-cacher-ng-docker/Dockerfile
    - name: docker-compose up -d
      docker_compose:
        project_src: /root/utility
        remove_orphans: true
        pull: true
        build: true
