---
- hosts: utility
  remote_user: root
  tasks:
    - name: docker
      include: includes/docker.yml
      static: false
      when: "ansible_distribution != 'Fedora'"
    - name: utility directory
      file:
        path: /root/utility
        state: directory
    - name: related files
      synchronize:
        src: ./files/utility/
        dest: /root/utility
    - name: docker-compose up -d
      docker_service:
        project_src: /root/utility
        remove_orphans: true
        pull: true
