---
- hosts: worker
  remote_user: nanahira
  #roles:
  #  - init
  tasks:
    - name: ansible
      become: true
      synchronize:
        src: ~/ansible/
        dest: '{{ansible_user_dir}}/ansible'
        delete: true
