---
- hosts: worker
  remote_user: nanahira
  roles:
    - init
  tasks:
    - name: ssh
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/
        mode: 0600
    - name: ssh
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/
        mode: 0600
    - name: remove old ansible
      become: true
      apt:
        name: ansible,awscli
        autoremove: true
        purge: true
        state: absent
    - name: install pip packages
      become: true
      pip:
        name: ansible,awscli
        state: latest
    - name: ansible
      synchronize:
        src: ~/ansible/
        dest: ~/ansible
        delete: true
    - name: aws
      synchronize:
        src: ~/.aws/
        dest: ~/.aws
        delete: true
    #- name: premake5 sync
    #  become: true
    #  copy:
    #    src: /usr/bin/premake5
    #    dest: /usr/bin/premake5
    #    mode: 0755
