---
- hosts: worker
  remote_user: nanahira
  #roles:
  #  - init
  tasks:
    - name: ssh
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/
        mode: 0600
    - name: ssh
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/
        mode: 0600
    - name: remove old ansible
      become: true
      apt:
        name: ansible,awscli
        autoremove: true
        purge: true
        state: absent
    - name: some apt packages
      become: true
      apt:
        update_cache: true
        name: ocserv,apache2-utils
    - name: upgrade pip
      become: true
      pip:
        name: pip
        state: latest
    - name: install pip packages
      become: true
      pip:
        name: ansible==2.9,awscli
        state: latest
    - name: ansible
      synchronize:
        src: ~/ansible/
        dest: ~/ansible
        delete: true
    - name: aws
      synchronize:
        src: ~/.aws/
        dest: ~/.aws
        delete: true
    - name: npm
      copy:
        src: ~/.npmrc
        dest: ~/.npmrc
    #- name: premake5 sync
    #  become: true
    #  copy:
    #    src: /usr/bin/premake5
    #    dest: /usr/bin/premake5
    #    mode: 0755
