---
- hosts: worker
  remote_user: nanahira
  tasks:
    - name: ssh
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/
        mode: 0600
    - name: ssh
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/
        mode: 0600
    - name: apt
      become: true
      apt:
        name: awscli,python,python3,python-pip,python3-pip
        state: latest
        update_cache: true
    - name: remove old ansible
      become: true
      apt:
        name: ansible
        autoremove: true
        state: absent
    - name: upgrade pip
      become: true
      pip:
        name: pip
        state: latest
        extra_args: -i https://mirrors.aliyun.com/pypi/simple/
    - name: install ansible
      become: true
      pip:
        name: ansible
        state: latest
        extra_args: -i https://mirrors.aliyun.com/pypi/simple/
    - name: ansible
      synchronize:
        src: ~/ansible/
        dest: ~/ansible
        delete: true
    - name: aws
      synchronize:
        src: ~/.aws/
        dest: ~/.aws
        delete: true
    #- name: premake5 sync
    #  become: true
    #  copy:
    #    src: /usr/bin/premake5
    #    dest: /usr/bin/premake5
    #    mode: 0755
