---
- name: basic packages for node
  become: true
  apt:
    update_cache: true
    state: latest
    name: curl,apt-transport-https,lsb-release,gnupg
  when: "ansible_os_family == 'Debian'"
- name: node apt key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  when: "(ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 18) or (ansible_distribution == 'Debian' and ansible_distribution_major_version|int < 9)"
- name: nodesource
  become: true
  with_items:
    - deb
    - deb-src
  apt_repository:
    filename: nodesource
    repo: '{{item}} https://deb.nodesource.com/node_{{nodejs_version}}.x {{ansible_distribution_release}} main'
  when: "(ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 18) or (ansible_distribution == 'Debian' and ansible_distribution_major_version|int < 9)"
- name: nodejs from nodesource
  become: true
  apt:
    state: latest
    name: nodejs
  when: "(ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 18) or (ansible_distribution == 'Debian' and ansible_distribution_major_version|int < 9)"
- name: nodejs from apt
  become: true
  apt:
    state: latest
    name: npm
  when: "(ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 18) or (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 9)"
- name: epel 7
  become: true
  yum:
    state: latest
    update_cache: true
    name: epel-release
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7"
- name: nodejs from yum
  become: true
  yum:
    state: latest
    update_cache: true
    name: npm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7"
- name: epel 8
  become: true
  dnf:
    state: latest
    name: epel-release
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
- name: nodejs from dnf
  become: true
  dnf:
    state: latest
    name: nodejs,npm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8"
- name: npm
  become: true
  npm:
    name: 'n'
    state: latest
    registry: https://registry.npm.taobao.org
    global: true
- name: nodejs version
  become: true
  shell: 'env NODE_MIRROR=https://npm.taobao.org/mirrors/node/ n {{nodejs_version}}'
- name: node setcap
  become: true
  with_items: ['/usr/bin/node', '/usr/local/bin/node']
  shell: 'setcap cap_net_bind_service=+eip {{item}}'
  when: "ansible_user_id != 'root'"
- name: npm
  become: true
  with_items:
    - npm
    - pm2
  npm:
    name: '{{item}}'
    state: latest
    registry: https://registry.npm.taobao.org
    global: true
- name: fixup npm directory
  become: true
  file:
    path: ~/.npm
    owner: '{{ansible_user_id}}'
    group: '{{ansible_user_id}}'
    recurse: true
